dist: trusty
sudo: false
script: bundle exec rake
before_script: ${PHANTOMJS:-phantomjs} --version

rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - jruby-9.1.16.0
gemfile:
  - Gemfile
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - POLTERGEIST_TEST_HOST=poltergeist.test.com

addons:
  hosts:
    # Used to test custom host driver feature
    - poltergeist.test.com

matrix:
  include:
<<<<<<< HEAD
    - rvm: 2.5.1
      gemfile: gemfiles/Gemfile.capy2
    - rvm: 2.5.1
      gemfile: gemfiles/Gemfile.capybara_master
  allow_failures:
    - gemfile: gemfiles/Gemfile.capybara_master
    - rvm: jruby-9.1.16.0
