dist: trusty
sudo: false
script: bundle exec rake
before_script: ${PHANTOMJS:-phantomjs} --version
before_install:
   - mkdir -p travis-phantomjs2
   - if [ ! -f $PWD/travis-phantomjs2/phantomjs ]; then wget https://github.com/Pyppe/phantomjs2.0-ubuntu14.04x64/raw/master/bin/phantomjs -O $PWD/travis-phantomjs2/phantomjs; fi
   - chmod +x $PWD/travis-phantomjs2/phantomjs
   - gem update bundler
cache:
  directories:
    - $PWD/travis-phantomjs2

rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.1.10
gemfile:
  - Gemfile
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - POLTERGEIST_TEST_HOST=poltergeist.test.com

addons:
  hosts:
    # Used to test custom host driver feature
    - poltergeist.test.com

matrix:
  include:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.1_9_3
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.1_9_3
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.2_0_0
    - rvm: 2.2.9
      gemfile: Gemfile
      env: PHANTOMJS=$PWD/travis-phantomjs2/phantomjs
    - rvm: 2.5.0
      gemfile: gemfiles/Gemfile.capybasra_master
    - rvm: jruby-9.1.16.0
      gemfile: Gemfile
  allow_failures:
    - gemfile: gemfiles/Gemfile.capybara_master
    - rvm: jruby-9.1.16.0
